# Source of truth for the research universe. Scores are FLOW analyst judgments (RESEARCH HYPOTHESIS),
# 1-10 scale, based on public information up to mid-2026. Scenario returns are 3-year total-return ranges' midpoints.
# g=growth q=quality v=valuation attractiveness m=momentum(mid-2026) c=catalysts o=optionality b=balance sheet
# x=expectation gap (market misunderstanding) s=volatility (10 = most volatile)
U = [
 ("NVDA","NVIDIA","Semiconductors","~$4-5T","AI accelerator + software platform (CUDA) with networking attached",
  dict(g=9,q=10,v=5,m=7,c=8,o=7,b=9,x=4,s=7),(-45,25,70,150),
  "Dominant AI compute platform; software lock-in and networking make it a system vendor, not a chip vendor.",
  "AI capex keeps compounding; inference demand broadens to enterprises and sovereigns; margins hold ~70%+.",
  "Hyperscaler capex digestion, custom ASIC share gains, export controls, cyclical gross-margin compression.",
  "Two consecutive quarters of falling data-center revenue with guidance cut, or gross margin < 65%.",
  ["Next-gen platform ramp","Hyperscaler capex guides","Sovereign AI deals"],"Very high growth, net cash, ~mid-20s to 30s forward P/E (approx)."),
 ("MSFT","Microsoft","Software","~$3.5-4T","Enterprise distribution + Azure + Copilot monetization",
  dict(g=7,q=10,v=5,m=5,c=6,o=6,b=10,x=4,s=3),(-25,30,60,95),
  "The default enterprise AI distribution channel with the strongest balance sheet in software.",
  "Azure AI growth sustains 30%+; Copilot attach becomes a material revenue line.",
  "AI capex depresses FCF; Copilot adoption slower than priced; OpenAI relationship friction.",
  "Azure growth decelerating below 20% while capex keeps rising.",
  ["Azure quarterly growth","Copilot seat disclosures"],"Low-teens revenue growth, ~45% operating margin, AAA balance sheet (approx)."),
 ("GOOGL","Alphabet","Internet","~$2.5-3.5T","Search + YouTube + Cloud + TPUs + Waymo optionality",
  dict(g=7,q=9,v=7,m=6,c=7,o=9,b=10,x=7,s=5),(-30,40,85,160),
  "Market priced it as an AI loser; it owns models, chips (TPU), cloud, distribution and Waymo.",
  "Search holds share while Cloud and TPU revenue accelerate; Waymo valued as a separate business.",
  "AI answers erode search ad pricing; antitrust remedies; capex intensity.",
  "Paid-click growth turns negative for 2+ quarters with no offset from Cloud.",
  ["Antitrust remedy rulings","Waymo city expansion","Cloud margin"],"Low-teens growth, ~30%+ op margin, lowest P/E of mega-cap tech (approx)."),
 ("AMZN","Amazon","Internet / Cloud","~$2-2.5T","AWS + retail margin expansion + advertising",
  dict(g=7,q=8,v=6,m=5,c=6,o=7,b=8,x=5,s=5),(-30,35,75,130),
  "Retail margins still expanding from automation; AWS re-accelerating with AI; ads quietly huge.",
  "Robotics drive retail margin toward high single digits; AWS grows 20%+.",
  "AWS loses AI workloads to Azure/neoclouds; consumer slowdown; heavy capex.",
  "AWS growth < 12% for multiple quarters.",
  ["AWS growth","Robotics/fulfillment cost disclosures"],"~10% growth, rising operating margins (approx)."),
 ("META","Meta Platforms","Internet","~$1.5-2T","Ads engine + AI-driven targeting; Reality Labs optionality",
  dict(g=8,q=9,v=6,m=5,c=6,o=7,b=9,x=5,s=6),(-35,30,70,120),
  "AI directly improves ad ROI today; 3B+ daily users is unmatched distribution.",
  "Ad growth sustains high teens; capex efficiency improves; AI assistants monetize.",
  "Capex surge without matching revenue; regulatory/teen-safety actions; Reality Labs losses.",
  "Ad impression pricing falls while capex guidance rises again.",
  ["Capex guidance","Ad pricing trends"],"High-teens growth, ~40% op margin (approx)."),
 ("TSM","Taiwan Semiconductor","Semiconductors","~$1-1.5T","Monopoly-like leading-edge foundry",
  dict(g=8,q=10,v=7,m=6,c=7,o=5,b=9,x=6,s=5),(-40,40,80,130),
  "Every AI chip, regardless of designer, is likely made by TSMC; discount exists mainly for geopolitics.",
  "Leading-edge pricing power plus advanced packaging (CoWoS) capacity ramp.",
  "Taiwan geopolitical risk is a true tail; US fab margin dilution; cycle downturn.",
  "Any blockade/conflict signal; leading-edge share loss to Intel/Samsung.",
  ["Monthly revenue reports","2nm ramp"],"~25-35% growth, ~45% op margin, P/E below US peers (approx)."),
 ("AVGO","Broadcom","Semiconductors","~$1-1.5T","Custom AI ASICs + networking + VMware cash flows",
  dict(g=8,q=9,v=4,m=7,c=7,o=6,b=6,x=4,s=6),(-40,20,60,110),
  "The main beneficiary if hyperscalers shift from GPUs to custom silicon.",
  "Custom accelerator revenue grows with 3+ hyperscaler programs.",
  "Lumpy customer concentration; acquisition debt; premium valuation.",
  "Loss of a top custom-silicon customer.",
  ["AI revenue guidance","New ASIC customers"],"Strong FCF, elevated debt from VMware (approx)."),
 ("ASML","ASML","Semi equipment","~$300-400B","Sole supplier of EUV lithography",
  dict(g=6,q=10,v=6,m=4,c=6,o=5,b=9,x=6,s=5),(-30,30,65,100),
  "A true monopoly on EUV; cyclical air pockets create entry points.",
  "High-NA EUV adoption and memory/logic capex upcycle in 2027.",
  "China export restrictions; customer capex delays; cyclicality.",
  "Orders decline for 3+ quarters with High-NA delays.",
  ["Quarterly bookings","Export-rule changes"],"Mid-teens margins expansion potential (approx)."),
 ("AMD","Advanced Micro Devices","Semiconductors","~$250-400B","Second-source AI GPUs + CPU share gains",
  dict(g=8,q=7,v=5,m=6,c=8,o=8,b=8,x=6,s=8),(-50,25,90,200),
  "Hyperscalers want a second GPU supplier; any meaningful share is a large revenue swing.",
  "MI-series GPUs win multi-GW deployments; server CPU share keeps rising.",
  "Software gap vs CUDA; execution risk; high multiple on forward hopes.",
  "AI GPU revenue guidance cut or a marquee deployment cancelled.",
  ["AI GPU ramps","Large customer announcements"],"Rapid growth from AI, moderate margins (approx)."),
 ("MU","Micron Technology","Semiconductors","~$150-250B","HBM memory for AI accelerators",
  dict(g=8,q=6,v=7,m=7,c=7,o=6,b=7,x=6,s=9),(-55,30,90,180),
  "HBM changed memory from commodity to constrained supply; cycle may be longer than history suggests.",
  "HBM share gains + tight DRAM supply extend the upcycle.",
  "Memory is brutally cyclical; supply additions crush pricing.",
  "DRAM contract prices fall two quarters in a row.",
  ["HBM qualification","DRAM pricing"],"Cyclical earnings near peak margins (approx)."),
 ("ANET","Arista Networks","Networking","~$150-200B","Ethernet switching for AI clusters",
  dict(g=8,q=9,v=4,m=6,c=6,o=6,b=10,x=5,s=7),(-40,25,65,110),
  "AI back-end networks moving to Ethernet; best-in-class software and margins.",
  "Ethernet wins scale-out AI networks at hyperscalers.",
  "NVIDIA networking competition; customer concentration; premium multiple.",
  "Major cloud customer shifts to in-house or NVIDIA networking.",
  ["AI networking revenue targets"],"~25% growth, ~40% op margin, net cash (approx)."),
 ("VRT","Vertiv","Industrials (data-center power/cooling)","~$40-60B","Power and liquid cooling for AI data centers",
  dict(g=8,q=7,v=5,m=7,c=7,o=6,b=6,x=6,s=8),(-50,30,80,150),
  "Second-order AI beneficiary: every GPU needs power and cooling; liquid cooling is a step change.",
  "Backlog converts at expanding margins as liquid cooling becomes standard.",
  "Data-center build pause; execution; competition from Schneider/Eaton.",
  "Book-to-bill below 1 for two quarters.",
  ["Backlog and orders","Margin targets"],"Strong orders backlog, moderate leverage (approx)."),
 ("GEV","GE Vernova","Power equipment","~$150-200B","Gas turbines, grid equipment, wind",
  dict(g=7,q=7,v=4,m=8,c=7,o=6,b=8,x=4,s=6),(-35,25,60,100),
  "Electricity demand growth (AI, electrification) meets sold-out gas turbine capacity.",
  "Pricing power on turbines and grid equipment through 2028.",
  "Wind losses; capacity additions normalize pricing; already-priced success.",
  "Turbine order pricing flattens or backlog shrinks.",
  ["Turbine slot reservations","Grid orders"],"Rapidly improving margins, net cash (approx)."),
 ("CEG","Constellation Energy","Utilities (nuclear)","~$80-120B","Largest US nuclear fleet; PPAs with hyperscalers",
  dict(g=6,q=7,v=4,m=6,c=7,o=6,b=6,x=4,s=6),(-35,20,55,90),
  "Carbon-free 24/7 power is scarce; hyperscaler contracts reprice an old fleet.",
  "More long-term data-center PPAs at premium prices.",
  "Power-price normalization; regulatory pushback on co-location; acquisition integration.",
  "FERC/state rules block behind-the-meter deals and power prices fall.",
  ["New PPAs","Regulatory rulings"],"Utility-like balance sheet, merchant price exposure (approx)."),
 ("LLY","Eli Lilly","Pharma","~$700B-1T","GLP-1 obesity franchise + oral pipeline",
  dict(g=9,q=9,v=4,m=5,c=8,o=7,b=7,x=4,s=5),(-35,25,60,100),
  "Obesity may become the largest drug category ever; Lilly leads on efficacy and supply.",
  "Oral GLP-1 approval and broad Medicare/insurer coverage.",
  "Price cuts from policy, compounded copies, competition; premium multiple.",
  "Oral pipeline failure plus significant US price compression.",
  ["Orforglipron launch","Coverage decisions"],"30%+ growth, high margins (approx)."),
 ("NVO","Novo Nordisk","Pharma","~$200-300B","GLP-1 incumbent that lost momentum",
  dict(g=4,q=8,v=8,m=2,c=6,o=6,b=7,x=7,s=6),(-35,30,70,110),
  "Contrarian: priced as a loser after pipeline and US share disappointments; still a huge cash generator.",
  "Stabilized share, cheaper valuation re-rates with next-gen pipeline data.",
  "Continued share loss to Lilly, price cuts, management turnover.",
  "Revenue declines for full year with no pipeline win.",
  ["Pipeline readouts","US pricing"],"Slowing growth, cheap vs history (approx)."),
 ("UNH","UnitedHealth","Healthcare services","~$250-350B","Largest US insurer + Optum",
  dict(g=4,q=7,v=8,m=2,c=5,o=4,b=6,x=7,s=6),(-40,30,65,90),
  "Contrarian special situation: earnings reset, legal/regulatory overhang, depressed multiple.",
  "Medical cost trend normalizes; margins recover toward historical range.",
  "DOJ investigations, Medicare Advantage rate pressure, structural cost trend.",
  "Guidance cut again or adverse DOJ outcome.",
  ["Medicare rate notices","Investigations"],"Earnings trough, low P/E vs history (approx)."),
 ("ISRG","Intuitive Surgical","Medtech","~$150-200B","Surgical robotics razor/blade model",
  dict(g=7,q=10,v=3,m=5,c=5,o=5,b=10,x=3,s=4),(-30,20,50,80),
  "Recurring instruments revenue on a growing installed base; deep moat.",
  "da Vinci 5 upgrade cycle, international growth.",
  "Valuation, competition from Medtronic/J&J, GLP-1 reducing bariatric procedures.",
  "Procedure growth below 10%.",
  ["Procedure growth"],"Mid-teens growth, net cash (approx)."),
 ("BRK.B","Berkshire Hathaway","Conglomerate","~$1T","Diversified cash generator with huge cash pile",
  dict(g=4,q=9,v=7,m=4,c=4,o=5,b=10,x=4,s=2),(-15,25,45,60),
  "Defensive compounding with optionality in its cash pile during a crisis.",
  "Large accretive deployment of cash in a downturn.",
  "Succession; low growth; cash drag in bull markets.",
  "Persistent underperformance plus value-destroying capital allocation.",
  ["Capital deployment"],"Fortress balance sheet (approx)."),
 ("V","Visa","Payments","~$600-700B","Global card network toll road",
  dict(g=6,q=10,v=5,m=5,c=4,o=4,b=9,x=3,s=3),(-20,25,50,70),
  "Toll on global consumer spending; ~65% operating margins.",
  "Cross-border travel and value-added services keep low-teens growth.",
  "Stablecoins/real-time payments, interchange regulation.",
  "Legislation that caps interchange broadly.",
  ["Regulation","Cross-border volumes"],"~10% growth, ~65% op margin (approx)."),
 ("COST","Costco","Retail","~$400-450B","Membership warehouse retail",
  dict(g=6,q=10,v=2,m=4,c=3,o=3,b=10,x=2,s=3),(-25,15,35,55),
  "Highest-quality retailer; membership fees are recurring.",
  "Steady unit growth and fee increases.",
  "Valuation ~50x leaves no room for error.",
  "Comparable sales < 3% for several quarters.",
  ["Membership fee changes"],"High-single-digit growth, rich P/E (approx)."),
 ("CRWD","CrowdStrike","Cybersecurity","~$100-130B","Endpoint security platform",
  dict(g=8,q=8,v=2,m=6,c=5,o=6,b=9,x=3,s=7),(-50,15,55,100),
  "Platform consolidation winner in security.",
  "Module adoption drives 20%+ ARR growth.",
  "Very high multiple; competition from Microsoft/Palo Alto.",
  "Net new ARR declining year over year.",
  ["Net new ARR"],"~20% growth, strong FCF margin, high valuation (approx)."),
 ("PLTR","Palantir","Software","~$300-450B","AI decision platform for government + enterprise",
  dict(g=10,q=8,v=1,m=8,c=6,o=8,b=10,x=2,s=10),(-70,0,50,120),
  "Fastest-growing large software company, but valuation implies perfection.",
  "US commercial growth sustains 50%+ for years.",
  "Extreme multiple; any deceleration compresses valuation violently.",
  "US commercial growth below 30%.",
  ["Government contracts","Commercial growth"],"40%+ growth, P/S among highest in large caps (approx)."),
 ("NFLX","Netflix","Media","~$400-500B","Global streaming + ads",
  dict(g=7,q=9,v=4,m=5,c=5,o=5,b=8,x=4,s=5),(-30,25,55,85),
  "Won the streaming war; ad tier and pricing power lift margins.",
  "Operating margin toward 35%+, ads scale.",
  "Content cost inflation; engagement shifting to YouTube/short video.",
  "Engagement hours decline two years running.",
  ["Ad revenue","Price increases"],"Low-teens growth, rising margins (approx)."),
 ("UBER","Uber","Mobility","~$150-200B","Ride-hailing + delivery network; AV aggregator",
  dict(g=7,q=7,v=6,m=5,c=6,o=7,b=7,x=7,s=6),(-45,30,75,130),
  "Market fears robotaxis disrupt it; Uber may instead be the demand aggregator for AV fleets.",
  "AV partners use Uber's network; FCF and buybacks compound.",
  "Tesla/Waymo go direct; regulatory labor reclassification.",
  "Major AV operator scales without Uber and takes share in core cities.",
  ["AV partnerships","FCF"],"Mid-teens growth, strong FCF (approx)."),
 ("MELI","MercadoLibre","E-commerce / fintech","~$100-130B","Latin American commerce + payments + credit",
  dict(g=8,q=8,v=5,m=5,c=5,o=7,b=6,x=5,s=7),(-45,35,80,140),
  "Amazon + PayPal of Latin America with long runway.",
  "Fintech credit book scales profitably; logistics moat widens.",
  "Credit losses, currency swings (ARS/BRL), political risk.",
  "Non-performing loans spike with margin compression.",
  ["Credit quality","Brazil/Mexico growth"],"30%+ growth, FX exposure (approx)."),
 ("SPOT","Spotify","Media","~$100-150B","Audio platform with pricing power",
  dict(g=7,q=7,v=4,m=5,c=5,o=5,b=8,x=4,s=6),(-40,20,55,90),
  "Shifted from growth-at-all-costs to margins; price increases stick.",
  "Margins expand toward 15%+ with audiobooks/ads.",
  "Label economics; premium valuation.",
  "Subscriber churn after price hikes.",
  ["Price increases","Margins"],"Mid-teens growth (approx)."),
 ("RKLB","Rocket Lab","Space","~$15-35B","Launch + spacecraft components; Neutron rocket",
  dict(g=9,q=5,v=2,m=8,c=8,o=10,b=6,x=4,s=10),(-75,10,120,400),
  "Lottery-like optionality: the only credible small/medium launch + space systems contender besides SpaceX.",
  "Neutron flies reliably and wins constellation/defense launches.",
  "Neutron delays/failure, cash burn, dilution, SpaceX pricing.",
  "Neutron failure plus major customer loss.",
  ["Neutron first flights","Defense contracts"],"Unprofitable, high growth, very high valuation (approx)."),
 ("IONQ","IonQ","Quantum computing","~$10-25B","Trapped-ion quantum systems",
  dict(g=8,q=3,v=1,m=6,c=6,o=10,b=7,x=3,s=10),(-85,-30,80,500),
  "Pure lottery ticket on quantum advantage arriving early.",
  "Commercial quantum advantage demonstrated with paying workloads.",
  "Technology may be a decade away; heavy dilution; valuation on narrative.",
  "No commercially useful advantage by 2028.",
  ["Technical milestones"],"Tiny revenue vs valuation, cash from equity raises (approx)."),
 ("XOM","Exxon Mobil","Energy","~$450-550B","Integrated oil major; Guyana + Permian",
  dict(g=4,q=7,v=7,m=7,c=5,o=4,b=9,x=4,s=5),(-30,20,45,70),
  "With WTI ~$96 (Sep 2026), cash returns are large; low-cost barrels and balance sheet.",
  "Oil stays above $80; Guyana growth adds volume.",
  "Oil price collapse; energy transition demand risk.",
  "WTI < $60 for a sustained period.",
  ["Oil price","Guyana production"],"Cyclical; low debt (approx)."),
]
